version: 2.1

orbs:
  win: circleci/windows@2.2.0

jobs:
  build:
    executor: win/default

    steps:
      - checkout

      - run:
          name: Setup Environment
          command: |
            choco install GitVersion.Portable

      - run:
          name: Install Wurst
          command: |
            $pathWithWurst = "{0};{1}\.wurst\" -f [System.Environment]::GetEnvironmentVariable("Path", [EnvironmentVariableTarget]::Machine), $env:USERPROFILE
            [System.Environment]::SetEnvironmentVariable("Path", $pathWithWurst, [EnvironmentVariableTarget]::Machine)
            java -jar .\build\WurstSetup.jar install wurstscript

      - run:
          name: Generate Wurst Build Configuration
          command: |
            Push-Location build
            .\GenerateWurstBuildFile.ps1
            Get-Content ..\wurst.build
            Pop-Location

      - run:
          name: Install Dependencies
          command: grill install

      - run:
          name: Run Map Pipeline
          command: |
            Push-Location build
            .\RunPipeline.ps1
            Pop-Location

      - run:
          name: Run Wurst Tests
          command: grill test

      - run:
          name: Wurst Map Build
          command: |
            Push-Location build
            .\RunWurstBuild.ps1
            Pop-Location

      - run:
          name: Prepare Artifacts
          command: |
            Push-Location build
            .\PrepareArtifacts.ps1
            Pop-Location

      - store_artifacts:
          path: ./_artifacts/

workflows:
  version: 2
  main:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
                - develop
            tags:
              only: /^\d+\.\d+\.\d+$/